// The move audit (docs/moves-audit.md): the most-fielded attacks (the bot roster, data/bots/roster.json, plus the
// collection fixture), each with its shape before this branch (arena main ba2f52e: its kit file, else the old
// auto-kit families, which are still in autokit.ts) and now (the lexicon + the type flavour + the hand kit), and the
// gross old mismatches flagged.
//   npx vite-node tools/kits/audit.ts [--top 60] [--base ba2f52e]
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { familyFor, sizedShape } from '../../src/sim/autokit'
import { parseAttackText } from '../../src/sim/cardtext'
import { resolveKit } from '../../src/sim/kit'
import { archetypeFor } from '../../src/sim/lexicon'
import { ENERGY_TYPES, type CardData, type EnergyType, type Kit, type Shape } from '../../src/sim/types'
import { loadCards } from './cards'

const arg = (k: string, d: string) => (process.argv.includes(k) ? process.argv[process.argv.indexOf(k) + 1] : d)
const top = parseInt(arg('--top', '60'), 10)
const base = arg('--base', 'ba2f52e')
const root = resolve(__dirname, '../..')
const roster: CardData[] = JSON.parse(readFileSync(resolve(root, 'data/bots/roster.json'), 'utf8')).cards
const fixture: CardData[] = JSON.parse(readFileSync(resolve(root, 'tests/fixtures/collection.json'), 'utf8')).cards.flatMap((c: { data?: CardData }) => (c.data ? [c.data] : []))
const cards = new Map(loadCards().map((c) => [c.id, c]))

// how often each attack name is fielded, and one card that fields it (the first with a kit file, else the first)
const count = new Map<string, number>()
const example = new Map<string, string>()
for (const c of [...roster, ...fixture]) for (const a of c.attacks ?? []) {
  count.set(a.name, (count.get(a.name) ?? 0) + 1)
  if (!example.has(a.name) || (!existsSync(resolve(root, `data/kits/${example.get(a.name)}.json`)) && existsSync(resolve(root, `data/kits/${c.id}.json`)))) example.set(a.name, c.id)
}
const oldKit = (id: string): Kit | null => {
  try { return JSON.parse(execFileSync('git', ['show', `${base}:data/kits/${id}.json`], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })) } catch { return null }
}
const nowKit = (id: string): Kit | null => (existsSync(resolve(root, `data/kits/${id}.json`)) ? JSON.parse(readFileSync(resolve(root, `data/kits/${id}.json`), 'utf8')) : null)
const n = (s: Shape, k: string) => (typeof s[k] === 'number' ? (s[k] as number) : undefined)
function show(s: Shape): string {
  const p = s.path ? ` ~${s.path}` : ''
  const x = (k: string, l: string) => (n(s, k) !== undefined ? ` ${l}${n(s, k)}` : '')
  switch (s.kind) {
    case 'projectile': return `shot r${n(s, 'radius')} R${n(s, 'range')}${x('count', '×')}${x('pierce', 'p')}${x('blast', 'blast')}${p}`
    case 'beam': return `beam ${n(s, 'length')}×${n(s, 'width')}`
    case 'cone': return `cone R${n(s, 'range')} A${n(s, 'arc')}`
    case 'melee': return `melee R${n(s, 'range')} A${n(s, 'arc')}${x('lunge', 'l')}`
    case 'dash': return `dash D${n(s, 'distance')}${s.invulnerable === 0 ? '' : ' (i-frames)'}${x('blast', 'land')}${p}`
    case 'area': return `area@${s.at ?? 'self'} r${n(s, 'radius')}${x('count', '×')}${n(s, 'ticks') && (n(s, 'ticks') as number) > 1 ? ` ${n(s, 'ticks')}t` : ''}${p}`
    default: return s.kind
  }
}
const size = (s: Shape) => n(s, 'radius') ?? n(s, 'range') ?? n(s, 'width') ?? 0
function flags(name: string, dmg: number, o: Shape, now: Shape, arch: string): string {
  const f: string[] = []
  const close = new Set(['melee', 'cone'])
  const oKind = o.kind === 'area' ? `area@${o.at ?? 'self'}` : o.kind, nKind = now.kind === 'area' ? `area@${now.at ?? 'self'}` : now.kind
  if (oKind !== nKind && !(close.has(o.kind) && close.has(now.kind))) f.push(`**shape**: was a ${oKind}, reads as ${arch}`)
  if ((o.kind === 'area' || o.kind === 'cone') && dmg >= 100 && size(o) < 100) f.push('**tiny** for a big move')
  if (now.path && !o.path) f.push(`trajectory: ${now.path}`)
  void name
  return f.join('; ') || 'fits'
}

const names = [...count.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).slice(0, top)
if (process.argv.includes('--md')) {
  console.log(`# Move audit: the ${top} most-fielded attacks

Generated by \`npx vite-node tools/kits/audit.ts --top ${top} --md\` (docs/MOVES.md section 6). "Fielded" counts the
attack across the bot roster (\`data/bots/roster.json\`, ${roster.length} cards) and the collection fixture. *Before* is
arena main \`${base}\` (its kit file, else the old auto-kit families); *now* is this branch (the move lexicon, the
type flavour and the hand kit). \`(hand)\` marks a hand kit. A **shape** verdict is a gross old mismatch (another range
class than the name: close, a ring around you, ranged, aimed, self); **tiny** is a big move (100+) with an area or
cone under 100 px. \`~path\` is a trajectory.
`)
}
console.log(`| attack | fielded | e.g. | dmg | before (${base}) | now | archetype | verdict |\n|---|---:|---|---:|---|---|---|---|`)
let gross = 0
for (const [name, cnt] of names) {
  const id = example.get(name)!
  const card = cards.get(id)
  if (!card) continue
  const ai = (card.attacks ?? []).findIndex((a) => a.name === name)
  const a = card.attacks![ai]
  const p = parseAttackText(a.text, card.name)
  const dmg = parseInt(/\d+/.exec(a.damage ?? '')?.[0] ?? '0', 10)
  const ok = oldKit(id)
  const type = ((ENERGY_TYPES as string[]).includes(card.types?.[0] ?? '') ? card.types![0] : 'Colorless') as EnergyType
  const el = ((a.cost ?? []).find((x) => x && x !== 'Colorless' && x !== 'Free') ?? type) as EnergyType
  const oldShape: Shape = ok?.attacks?.find((x) => x.name === name)?.shape
    ?? sizedShape(familyFor(a, p, el, ai), (a.cost ?? []).length, dmg, el, p.post.some((e) => e.op === 'benchDamage'))
  const nowShape = resolveKit(card, nowKit(id)).attacks[ai].shape
  const arch = archetypeFor(name, p, dmg)?.id ?? '(type default)'
  const v = flags(name, dmg, oldShape, nowShape, arch)
  if (v.includes('**')) gross++
  console.log(`| ${name} | ${cnt} | ${card.name} | ${dmg || '-'} | ${show(oldShape)}${ok ? ' (hand)' : ''} | ${show(nowShape)}${nowKit(id) ? ' (hand)' : ''} | \`${arch}\` | ${v} |`)
}
console.log(`\n${names.length} attacks; ${gross} had a gross mismatch before (a shape of the wrong kind, or tiny for a big move).`)
